[package]
name = "app-quantus-rust"
version = "1.0.0"
authors = ["Ledger"]
edition = "2021"

[dependencies]
ledger_device_sdk = "1.*"
serde = { version="1.0.192", default-features = false, features = ["derive"] }
serde-json-core = "0.6.0"
hex = { version = "0.4.3", default-features = false, features = ["serde", "alloc"] }
numtoa = "0.2.4"
# qp-rusty-crystals-dilithium removed - now using C library (m4fstack) for lower memory usage
# qp-rusty-crystals-dilithium = { git = "https://github.com/Quantus-Network/qp-rusty-crystals.git", tag = "embedded_1_1", default-features = false , features=["embedded"]}
# qp-rusty-crystals-dilithium = { path = "/qp-rusty-crystals/dilithium", default-features = false, features = ["embedded"] }

# qp-rusty-crystals-hdwallet = { git = "https://github.com/Quantus-Network/qp-rusty-crystals.git", tag = "embedded_1_0", default-features = false, features = ["quantus_v1"] }
qp-poseidon-core = { version = "1.0.1", default-features = false, features = ["p3"] }
blake2 = { version = "0.10", default-features = false }
bs58 = { version = "0.5", default-features = false, features = ["alloc"] }

[build-dependencies]
image = "0.25.7"
cc = "1.0"

[features]
default = ["ledger_device_sdk/nano_nbgl", "debug"]
debug = ["ledger_device_sdk/debug"]

[package.metadata.ledger]
curve = ["secp256k1"]
flags = "0"
# path = ["m/44'/189189'/0'/0'/0'"] # Ledger seems to omit the m?!
path = ["44'/189189'/0'/0'/0'"]
name = "Quantus Network"

[package.metadata.ledger.stax]
icon = "icons/crab_32x32.gif"

[package.metadata.ledger.flex]
icon = "icons/crab_40x40.gif"

[package.metadata.ledger.apex_p]
icon = "icons/crab_32x32.png"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("apex_p", "stax", "flex"))'] }
